modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory
issueTrackerURL="https://github.com/MoriyaShiine/Respawnable-Pets/issues" #optional
[[mods]] #mandatory
modId="respawnablepets" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Respawnable Pets" #mandatory
displayURL="https://www.curseforge.com/minecraft/mc-mods/respawnable-pets" #optional
credits="cybercat5555 for textures" #optional
authors="MoriyaShiine" #optional
description='''A Minecraft mod that allows your pets to respawn'''
[[dependencies.respawnablepets]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.respawnablepets]]
        modId="minecraft"
        mandatory=true
        versionRange="[1.15.1]"
        ordering="NONE"
        side="BOTH"