modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/MoriyaShiine/respawnable-pets/issues"
[[mods]]
modId="respawnablepets"
version="${file.jarVersion}"
displayName="Respawnable Pets"
displayURL="https://minecraft.curseforge.com/projects/respawnable-pets"
logoFile="icon.png"
authors="MoriyaShiine, cybercat5555"
description='''A simple mod that allows your pets to respawn after death when you next sleep using a new item, the Etheric Gem.'''
[[dependencies.respawnablepets]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.respawnablepets]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"